<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>source.ck2.mod</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>name</key>
				<string>comment.line.number-sign.ck2.mod</string>
				<key>match</key>
				<string>#.*$</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s*([a-z][a-z_]*)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.other.ck2.mod</string>
					</dict>
				</dict>
			</dict>
			<dict>
				<key>begin</key>
				<string>(=)\s*</string>
				<key>end</key>
				<string>\s*$</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.structure.array.ck2.mod</string>
						<key>begin</key>
						<string>\{\s*</string>
						<key>end</key>
						<string>\s*\}</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#string</string>
							</dict>
							<dict>
								<key>name</key>
								<string>punctuation.separator.array.ck2.mod</string>
								<key>match</key>
								<string>\s+</string>
							</dict>
							<dict>
								<key>name</key>
								<string>invalid.illegal.ck2.mod</string>
								<key>match</key>
								<string>\S+</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>invalid.illegal.ck2.mod</string>
						<key>match</key>
						<string>.+</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>string</key>
			<dict>
				<key>name</key>
				<string>string.quoted.double.ck2.mod</string>
				<key>begin</key>
				<string>"</string>
				<key>end</key>
				<string>"</string>
			</dict>
		</dict>
	</dict>
</plist>
