<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>source.ck2</string>
		<key>foldingStartMarker</key>
		<string>\{\s*$</string>
		<key>foldingStopMarker</key>
		<string>^\s*\}</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>name</key>
				<string>comment.line.number-sign.ck2</string>
				<key>match</key>
				<string>#.*$</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.control.ck2</string>
				<key>match</key>
				<string>\b(?:ROOT|(?:FROM){1,4}|THIS|(?:PREV){1,4})\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.control.ck2</string>
				<key>match</key>
				<string>\b(?:OR|AND|NOT|NOR|NAND)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.numeric.ck2</string>
				<key>match</key>
				<string>\b-?\d+(?:\.\d+)?\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.language.ck2</string>
				<key>match</key>
				<string>\b(?:yes|no)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>string.quoted.double.ck2</string>
				<key>begin</key>
				<string>"</string>
				<key>end</key>
				<string>"</string>
			</dict>
			<dict>
				<key>name</key>
				<string>string.unquoted.ck2</string>
				<key>match</key>
				<string>\b[A-Z][\-A-Z_]*\b</string>
			</dict>
			<dict>
				<key>match</key>
				<string>([a-z][0-9a-z_]*)\s*=</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.other.ck2</string>
					</dict>
				</dict>
			</dict>
		</array>
	</dict>
</plist>
